use base64::engine::general_purpose::STANDARD as BASE64;
use base64::Engine;
use serde::{Deserialize, Serialize};

use crate::error::SecureCoreError;

/// Current supported schema version for `WrapsEnvelope`.
pub const WRAPS_SCHEMA_VERSION: &str = "1.1";

/// Known wrapping algorithm identifiers.
pub const ALGO_AES_256_GCM_KEYSTORE: &str = "AES-256-GCM-KEYSTORE";
pub const ALGO_AES_256_GCM_KEYCHAIN: &str = "AES-256-GCM-KEYCHAIN";

/// Metadata associated with an encrypted document.
///
/// This struct is designed to be serialized to JSON and stored by the platform
/// alongside the encrypted file. The core never persists it — that is the
/// platform's responsibility (see `docs/platform-contract.md`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DocumentMetadata {
    /// Unique document identifier (UUID recommended).
    pub doc_id: String,

    /// Original filename.
    pub filename: String,

    /// MIME type of the original file (e.g. "image/jpeg").
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,

    /// Unix timestamp (seconds) when the document was encrypted.
    pub created_at: u64,

    /// Size of the original plaintext in bytes.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plaintext_size: Option<u64>,

    /// Size of the encrypted output in bytes.
    pub ciphertext_size: u64,

    /// SHA-256 hash of the plaintext (optional integrity check).
    #[serde(
        skip_serializing_if = "Option::is_none",
        serialize_with = "serialize_optional_hash",
        deserialize_with = "deserialize_optional_hash",
        default
    )]
    pub content_hash: Option<[u8; 32]>,

    /// Free-form tags for document categorization (e.g. "Finance", "Santé").
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tags: Option<Vec<String>>,

    /// Optional folder assignment. None = vault root, Some(id) = belongs to folder.
    /// Absent in pre-folder JSON — deserialized as None for backward compatibility.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub folder_id: Option<String>,

    /// The wrapped (encrypted) DEK envelope.
    pub wrapped_dek: WrapsEnvelope,
}

/// Metadata for a virtual folder in the vault.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FolderMetadata {
    /// Unique folder identifier (UUID v4, generated by the platform).
    pub id: String,

    /// Display name (1–64 UTF-8 characters).
    pub name: String,

    /// Unix timestamp (milliseconds) when the folder was created.
    pub created_at: u64,

    /// Unix timestamp (milliseconds) when the folder was last updated.
    pub updated_at: u64,
}

/// Canonical envelope for a wrapped DEK.
///
/// See `docs/wraps-schema-v1.md` for the frozen specification.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct WrapsEnvelope {
    /// Schema version (must be "1.1" for V1).
    pub schema_version: String,

    /// Device-local wrap using OS keystore. MUST NOT be None.
    pub device: Option<DeviceWrap>,

    /// Recovery wrap for cross-device restore. null/None in V1.
    pub recovery: Option<serde_json::Value>,
}

/// Device-local DEK wrap produced by the OS keystore.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DeviceWrap {
    /// Wrapping algorithm (e.g. "AES-256-GCM-KEYSTORE").
    pub algo: String,

    /// Alias of the master key in the OS keystore/keychain.
    pub key_alias: String,

    /// Base64-encoded initialization vector.
    pub iv: String,

    /// Base64-encoded authentication tag.
    pub tag: String,

    /// Base64-encoded ciphertext (wrapped DEK, without tag).
    pub ciphertext: String,
}

impl WrapsEnvelope {
    /// Creates a new V1 envelope with a device wrap.
    pub fn new_device(
        algo: String,
        key_alias: String,
        iv: Vec<u8>,
        tag: Vec<u8>,
        ciphertext: Vec<u8>,
    ) -> Self {
        Self {
            schema_version: WRAPS_SCHEMA_VERSION.to_string(),
            device: Some(DeviceWrap {
                algo,
                key_alias,
                iv: BASE64.encode(&iv),
                tag: BASE64.encode(&tag),
                ciphertext: BASE64.encode(&ciphertext),
            }),
            recovery: None,
        }
    }

    /// Validates the envelope structure.
    pub fn validate(&self) -> Result<(), SecureCoreError> {
        // Check schema version
        if self.schema_version != WRAPS_SCHEMA_VERSION {
            return Err(SecureCoreError::InvalidParameter(format!(
                "unsupported wraps schema_version: {} (expected {})",
                self.schema_version, WRAPS_SCHEMA_VERSION,
            )));
        }

        // device must be present
        let device = self.device.as_ref().ok_or_else(|| {
            SecureCoreError::InvalidParameter("device wrap must not be null".into())
        })?;

        // algo must be non-empty and known
        if device.algo.is_empty() {
            return Err(SecureCoreError::InvalidParameter(
                "device.algo must not be empty".into(),
            ));
        }

        // key_alias must be non-empty
        if device.key_alias.is_empty() {
            return Err(SecureCoreError::InvalidParameter(
                "device.key_alias must not be empty".into(),
            ));
        }

        // Validate base64 fields are decodable and correct sizes
        let iv_bytes = BASE64.decode(&device.iv).map_err(|e| {
            SecureCoreError::InvalidParameter(format!("device.iv: invalid base64: {e}"))
        })?;
        if iv_bytes.len() != 12 {
            return Err(SecureCoreError::InvalidParameter(format!(
                "device.iv must be 12 bytes, got {}",
                iv_bytes.len()
            )));
        }

        let tag_bytes = BASE64.decode(&device.tag).map_err(|e| {
            SecureCoreError::InvalidParameter(format!("device.tag: invalid base64: {e}"))
        })?;
        if tag_bytes.len() != 16 {
            return Err(SecureCoreError::InvalidParameter(format!(
                "device.tag must be 16 bytes, got {}",
                tag_bytes.len()
            )));
        }

        let ct_bytes = BASE64.decode(&device.ciphertext).map_err(|e| {
            SecureCoreError::InvalidParameter(format!("device.ciphertext: invalid base64: {e}"))
        })?;
        if ct_bytes.is_empty() {
            return Err(SecureCoreError::InvalidParameter(
                "device.ciphertext must not be empty".into(),
            ));
        }

        Ok(())
    }
}

impl DeviceWrap {
    /// Decodes the IV from base64.
    pub fn iv_bytes(&self) -> Result<Vec<u8>, SecureCoreError> {
        BASE64
            .decode(&self.iv)
            .map_err(|e| SecureCoreError::InvalidParameter(format!("device.iv: {e}")))
    }

    /// Decodes the tag from base64.
    pub fn tag_bytes(&self) -> Result<Vec<u8>, SecureCoreError> {
        BASE64
            .decode(&self.tag)
            .map_err(|e| SecureCoreError::InvalidParameter(format!("device.tag: {e}")))
    }

    /// Decodes the ciphertext from base64.
    pub fn ciphertext_bytes(&self) -> Result<Vec<u8>, SecureCoreError> {
        BASE64
            .decode(&self.ciphertext)
            .map_err(|e| SecureCoreError::InvalidParameter(format!("device.ciphertext: {e}")))
    }
}

impl DocumentMetadata {
    /// Validates that all required fields are present and well-formed.
    pub fn validate(&self) -> Result<(), SecureCoreError> {
        if self.doc_id.is_empty() {
            return Err(SecureCoreError::InvalidParameter(
                "doc_id must not be empty".into(),
            ));
        }
        if self.filename.is_empty() {
            return Err(SecureCoreError::InvalidParameter(
                "filename must not be empty".into(),
            ));
        }
        self.wrapped_dek.validate()
    }
}

// ── Hash serialization helpers ────────────────────────────────────────────

fn serialize_optional_hash<S: serde::Serializer>(
    val: &Option<[u8; 32]>,
    s: S,
) -> Result<S::Ok, S::Error> {
    match val {
        Some(hash) => {
            let hex: String = hash.iter().map(|b| format!("{b:02x}")).collect();
            s.serialize_some(&hex)
        }
        None => s.serialize_none(),
    }
}

fn deserialize_optional_hash<'de, D: serde::Deserializer<'de>>(
    d: D,
) -> Result<Option<[u8; 32]>, D::Error> {
    let opt: Option<String> = Option::deserialize(d)?;
    match opt {
        Some(hex) => {
            if hex.len() != 64 {
                return Err(serde::de::Error::custom(
                    "content_hash must be 64 hex chars",
                ));
            }
            let bytes: Vec<u8> = (0..hex.len())
                .step_by(2)
                .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).map_err(serde::de::Error::custom))
                .collect::<Result<_, _>>()?;
            let mut arr = [0u8; 32];
            arr.copy_from_slice(&bytes);
            Ok(Some(arr))
        }
        None => Ok(None),
    }
}
